name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Initialize and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Check submodule status
        run: git submodule status

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Create application.properties
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-build-cache

      - name: Check build directory
        run: ls -al build/libs

      - name: Verify JAR contents
        run: |
          unzip -l build/libs/baseball-back-0.0.1-SNAPSHOT.jar

      - name: Verify application.yml in JAR
        run: |
          unzip -l build/libs/baseball-back-0.0.1-SNAPSHOT.jar | grep "application.yml"

      - name: Verify application.properties in JAR
        run: |
          unzip -l build/libs/baseball-back-0.0.1-SNAPSHOT.jar | grep "application.properties"

      - name: Print application.properties content
        run: |
          unzip -p build/libs/baseball-back-0.0.1-SNAPSHOT.jar BOOT-INF/classes/application.properties

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/baseball2 .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/baseball2

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/baseball2

      - name: Stop and remove container using port 8080
        run: |
          CONTAINER_ID=$(sudo docker ps -q -f "publish=8080")
          if [ -n "$CONTAINER_ID" ]; then
            echo "Stopping container with ID $CONTAINER_ID"
            sudo docker stop "$CONTAINER_ID"
            echo "Removing container with ID $CONTAINER_ID"
            sudo docker rm "$CONTAINER_ID"
          else
            echo "No container is using port 8080"
          fi

      - name: Run new Docker container
        run: sudo docker run --name github-actions-demo -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/baseball2

      - name: Prune unused Docker images and volumes
        run: sudo docker system prune -f --volumes
